# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

parameters:  
  - name: buildDockerImage
    displayName: Build Docker Image
    type: boolean
    default: true

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      condition: ${{ parameters.buildDockerImage }}
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
      env:
        DOCKER_BUILDKIT: 1
    - task: Docker@2
      displayName: Test Docker Image
      condition: ${{ parameters.buildDockerImage }}
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        arguments: 
          --target test
      env:
        DOCKER_BUILDKIT: 1
    - task: Docker@2
      displayName: Push Docker image
      condition: ${{ parameters.buildDockerImage }}
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'mikeytaylor/azurepipelinespoc'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
      env:
        DOCKER_BUILDKIT: 1

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration release' # Update this to match your need
    - task: DotNetCoreCLI@2
      displayName: Run Unit Tests
      inputs:
        command: test
        projects: '**/*.csproj'
        arguments: '--configuration release' # Update this to match your need
        

